# Generated by Django 3.1.5 on 2021-01-07 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
